
var data = {
    "locations": [ "Toronto", "Brampton", "Hamilton"],
    "classes": [ "ENG 2MA3", "CHEM 4P03", "BIO 1B03" ],
    "textbooks": [  { "name": "Biology - Concepts and Connections", "author": "Campbell", "published": "1990-01-01", "price": 40, "course": "BIO 1A03", "src": "/image/bio_1.jpg", "rating": "☆☆☆☆" , "location": "Hamilton", "id": 0, "personId": 0, "flexible": false, "description": "New Texbook, trying to sell, just bought.", "userFavourited": false },
                    { "name": "Biology", "author": "Brooker", "published": "2002-03-21", "price": 60, "course": "BIO 1B03", "src": "/image/bio_2.jpg", "rating": "☆☆☆☆☆", "location": "Brampton", "id": 1, "personId": 1, "flexible": false, "description": "General biology textbook, probably used in more clases than I could think of to put.", "userFavourited": false },
                    { "name": "Human Biology", "author": "Michael D. Johnson", "published": "2008-03-21", "price": 90, "course": "BIO 3HB3", "src": "/image/bio_3.jpg", "rating": "☆☆☆☆", "location": "Toronto", "id": 2, "personId": 2, "flexible": true, "description": "Have you ever wondered how the human body works? This book is a great place to start.", "userFavourited": false },
                    { "name": "Exploring Biology in the Labratory", "author": "John L. Crawley", "published": "2018-06-14", "price": 110, "course": "BIO 2LA3", "src": "/image/bio_4.jpg", "rating": "☆☆☆", "location": "Brampton", "id": 3, "personId": 3, "flexible": false, "description": "Great book to help with biolabs, great 9/10 condition!", "userFavourited": false  },
                    { "name": "Organic Chemistry", "author": "Michael B. Smith", "published": "2000-11-04", "price": 40, "course": "CHEM 2OC3", "src": "/image/chemistry_1.jpg", "rating": "☆", "location": "Hamilton", "id": 4, "personId": 5, "flexible": true, "description": "5/10 condition, hence why the price is flexible.", "userFavourited": false },
                    { "name": "Conceptual Chemistry", "author": "John Suchocki", "published": "2008-03-21", "price": 60, "course": "CHEM 3CC3", "src": "/image/chemistry_2.jpg", "rating": "☆☆☆☆☆", "location": "Hamilton", "id": 5, "personId": 1, "flexible": false, "description": "10/10 Condition", "userFavourited": false },
                    { "name": "Physical Chemistry of Polymers", "author": "Sebastian Seiffert", "published": "2013-02-19", "price": 95, "course": "CHEM 4P03", "src": "/image/chemistry_3.jpg", "rating": "☆☆☆☆", "location": "Brampton", "id": 6, "personId": 2, "flexible": true, "description": "The figures in the book were amazing and helped me understand the course material so much better.", "userFavourited": false },
                    { "name": "Organic Chemistry 2", "author": "Francis A. Carey", "published": "2017-08-20", "price": 115, "course": "CHEM 2CO3", "src": "/image/chemistry_4.jpg", "rating": "☆☆☆", "location": "Toronto", "id": 7, "personId": 3, "flexible": false, "description": "Teaches you the fundamentals of organic chemistry. Two pages have rips, but otherwise good!", "userFavourited": false },
                    { "name": "Mathematics", "author": "Holt", "published": "2002-12-05", "price": 45, "course": "MATH 1XA3", "src": "/image/math_1.jpg", "rating": "☆☆", "location": "Hamilton", "id": 8, "personId": 4, "description": "2+2 is 4 - 1 thats 3 quick maths! After you read this textbook, you could be that fast!", "userFavourited": false },
                    { "name": "Geometry", "author": "Holt", "published": "2005-09-26", "price": 70, "course": "MATH 1XB3", "src": "/image/math_2.jpg", "rating": "☆", "location": "Hamilton", "id": 9, "personId": 5, "description": "If you love shapes, you'll love this book!", "userFavourited": false },
                    { "name": "Elementary Calculus", "author": "H. Jerome Keisler", "published": "2015-04-30", "price": 85, "course": "MATH 2C03", "src": "/image/math_3.jpg", "rating": "☆☆☆☆☆", "location": "Hamilton", "id": 10, "personId": 1, "flexible": false, "description": "This textbook is the only way i was able to pass this course hahaha.", "userFavourited": false },
                    { "name": "Essential Mathematics for Engineers", "author": "W. J. R. H Pooler", "published": "2019-11-16", "price": 120, "course": "ENG 2MA3", "src": "/image/math_4.jpg", "rating": "☆☆☆☆", "location": "Toronto", "id": 11, "personId": 2, "flexible": true, "description": "8/10 condition, need to sell asap.", "userFavourited": false },
                    { "name": "Essential Mathematics for Engineers", "author": "W. J. R. H Pooler", "published": "2019-11-16", "price": 100, "course": "ENG 2MA3", "src": "/image/math_4.jpg", "rating": "☆☆☆", "location": "Hamilton", "id": 12, "personId": 3, "flexible": false, "description": "10/10 condition, loved this book, but have to let it go.", "userFavourited": false }
                ],
    "people": [
        {"id": 0, "firstName": "Kevin", "lastName": "Browne", "gender": "Male", "email": "brownek@mcmaster.ca", "phone":"905-525-9140", "location": "Hamilton, ON", "avatar":"/image/browne.jpg", "favourited": [], "rating": "☆☆☆☆"},
        {"id": 1, "firstName": "King", "lastName": "Bach", "gender": "Male", "email": "bachk.5p00n@hotmail.com", "phone":"416-821-5211", "location": "Toronto, ON", "avatar":"/image/bach.jpg", "favourited": [3, 8], "rating": "☆☆☆☆☆"},
        {"id": 2, "firstName": "Anthony", "lastName": "Fantano", "gender": "Other", "email": "anthonyf@gmail.com", "phone":"647-929-3264", "location": "Hamilton, ON", "avatar":"/image/fantano.jpg", "favourited": [2, 8, 7], "rating": "☆☆☆☆"},
        {"id": 3, "firstName": "Ray-William", "lastName": "Johnson", "gender": "Male", "email": "yfm2011@yahoo.com", "phone":"905-800-5009", "location": "Hamilton, ON", "avatar":"/image/ray.jpg", "favourited": [0, 1, 11, 4], "rating": "☆☆☆"},
        {"id": 4, "firstName": "Janet", "lastName": "Kim", "gender": "Female", "email": "janetkim@gmail.com", "phone":"647-123-4567", "location": "Toronto, ON", "avatar":"/image/janet.jpg", "favourited": [4, 6, 7, 9, 10], "rating": "☆☆"},
        {"id": 5, "firstName": "Drew", "lastName": "Gooden", "gender": "Male", "email": "drewisgooden@outlook.com", "phone":"416-666-4205", "location": "Brampton, ON", "avatar":"/image/gooden.jpg", "favourited": [0, 1, 2, 3, 5, 6], "rating": "☆"}
    ]
}

export default data;
